### ISSUE TITLE
chore: After verifying the calls the counts don't decreased

### ISSUE THREAD

**Issue by a3bd2lra7man** [drashland/rhum#170] opened 2022-09-14 07:43 UTC
## Verifying the calls doesn't decreased the counts 

Hello there I'm really fan of your library and I wish I help you improving it,
So I found this problem

## What is the problem

I was writing unit test,
and while writing the first test it works fine and as expected,
but after writing the second test it was behaving wrongly, I got confused, and I did some the debug and found that the counts doesn't decreased after passing the first unit test 

let me explain with the code 

```ts
const mock = Mock(Collection).create(); // create a mock
const userDao = new UserDAO(mock);

Deno.test("test saving user throws UnAbleToWriteDatabase",
    async () => {
        mock.method("insertOne").willReturn(Promise.reject("saS"));

        try {
            await userDao.addUser(userMockObject);
            throwExceptionIfTestReachHere();
        } catch (e) {
            assertOfType(e, UnableToWriteOnDatabase);
        }
        mock.expects("insertOne").toBeCalled(1);
        mock.verifyExpectations();
    }
);
```

the previous code works fine 

but If I write another test EVEN IT'S THE SAME CODE IT WILL FAILS

```ts
Deno.test("test saving user throws UnAbleToWriteDatabase",
    async () => {
        mock.method("insertOne").willReturn(Promise.reject("saS"));

        try {
            await userDao.addUser(userMockObject);
            throwExceptionIfTestReachHere();
        } catch (e) {
            assertOfType(e, UnableToWriteOnDatabase);
        }
        mock.expects("insertOne").toBeCalled(1); // HERE THE ERROR WILL HAPPENED 
        mock.verifyExpectations();
    }
);
```

The exception will be 
error: Error: Method "insertOne" expected 1 call(s), but received 2 call(s).
          throw new MockError(

## that means that the counts doesn't decreased after verifying (I tried the other verifying way and it's the same)

As I said I'm really big fan of your library. All Lucks

**Comment by crookse** [comment] 2022-09-22 02:09
hi @a3bd2lra7man! thanks for raising this issue. i _think_ the issue is with the mock assignment you have. at the top, you create the mock and use the same mock in both of your tests. since the mock is the same, its properties will remain the same in each test (e.g., the calls property). what i think you should try is to create the mock in each test so that each test contains its own version of the mock. that way, the calls start at 0 for each test. let us know if this solves your problem. thanks!

**Comment by crookse** [comment] 2023-01-30 00:23
hi @a3bd2lra7man, closing this. feel free to re-open and discuss.

**Closed by crookse** 2023-01-30 00:23 UTC
